name: Autograding Tests
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Autoavaluacio
      id: autoavaluacio
      uses: education/autograding-command-grader@v1
      with:
        test-name: Autoavaluacio
        setup-command: ''
        command: gradle test
        timeout: 5
        max-score: 10
    - name: Autograding Reporter
      uses: education/autograding-grading-reporter@v1
      env:
        AUTOAVALUACIO_RESULTS: "${{steps.autoavaluacio.outputs.result}}"
      with:
        runners: autoavaluacio
